---
title: "Assignments"
output:
  html_document:
    toc: true
    toc_float: true
---

# Review and Chew

_Course Reading Discussion Groups_

## Purpose 

The “Review & Chew” discussion groups provide opportunities for students to reflect upon and discuss concepts presented in course readings in a small group setting. The opportunity to analyze, share ideas and ask questions deepens learning and enhances critical thinking.  

## Implementation 

Students will be organized into groups of 6. They will stay with their groups for the term. Reading questions will be posted on the course website by the beginning of the week. The questions are designed to guide reading and help students focus on key concepts. Students will be expected to post their responses to the Review & Chew prior to the start of class. During class, students will get into their groups and review their responses. Each “Review & Chew” group will have a facilitator for that session who will guide the discussion and write up a brief summary (bullet points with respect to questions that were discussed) on a piece of paper that will be turned in. The summary may list concepts where there was confusion or disagreement or high agreement or high interest. The facilitators will put their names at the top and then list participating group members.  

 
For two of the Review and Chew assigned readings, students will only need to read ONE of two assigned readings. They will email their group prior and decide who will read which article in order to have half read one and half read the other. The facilitator will note the differences between the interventions described in both articles on the summary sheet.  

## Grading 

There will be **_three_** “Review & Chew” group sessions each worth six points, for a total of 30  points. Every student will take one turn being facilitator and writing up the summary. For the two Review and Chew where a comparison of the two articles is required, there will be two facilitators. If students have an excused absence during a “Review & Chew” group, they can write up responses to the reading questions within 24 hours and receive a maximum of 2 points.  

 
**_Six points will be awarded for completeness and thoughtful analysis shown in written responses and evidence of active engagement in the discussion._**

## Questions

|**R&C**        | **Questions**                           | **Due**      |  
|:-------------:| :---------------------------------------|:------------:|  
| 1             |   [R&C 1](chews/Review&Chew_1.docx)                             |    1/14/21   | 
| 2             |   [R&C 2](chews/Review&Chew_2.docx)                             |    1/28/21   | 
| 3             |   [R&C 3](chews/Review&Chew_3.docx)                             |    2/11/21   | 





# Systematic Instruction Portfolio 

**_Description:_**  Students will develop an instructional portfolio designed to showcase their knowledge about how to train people with cognitive impairments in the use of assistive technology for cognition.  In most cases, students will be selecting an app to train, although some students may elect to develop a portfolio for training a specific device. Most students will be generating a hypothetical client and creating hypothetical data. The portfolio will include the following four sections. 

**Due:** 2/18/21 

## Section 1: Client Profile/Needs Assessment/Tool Selection 

This first section will be titled **Tool Selection**. Describe the factors that would be important for a complete Needs Assessment. Ultimately, the profile should provide a rationale for selecting the chosen app/device. The profile should begin with a client description and minimally include age, etiology, time post onset, medical diagnosis, cognitive profile, primary concerns, relevant contextual factors. Your client should have moderate or moderate-severe impairments affecting the ability to learn new information. Think about the key components of a Needs Assessment. You will want to provide sufficient information such that your portfolio matches your client profile. For example, a client with more severe impairments, may need more trials than a client with more mild-moderate impairments. This section will be about a page. You will likely want to construct a table to summarize your needs assessment and then supplement this information with narrative. Review the Needs Assessments from your text and in the slides to ensure that you cover the relevant areas to your client.  Use professional, clinically relevant language to describe your client. Provide citations in APA format as relevant.  

After you describe the client profile, you will write a one paragraph description of the app or device. Look at app reviews on line and look at categories that are rated (e.g., ease of use; clarity; helpfulness; compatibility etc.). What makes people use or not use an app? Part of the selection process is to MATCH the app or device with the profile of your client and make sure that the look and feel and functionality is a good fit.  

## Section 2: Goal Attainment Scale

The second section of your portfolio will be titled: **Goal Attainment Scale**. You will generate a hypothetical five level goal attainment scale that would provide an outcome measure for evaluating IMPACT of training your app or device. Your GAS will be evaluated to see if it meets the SMARTED criteria. Be sure to include Functional Domain, Cognitive Domain and Measurement Plan. This should be less than a page.  


## Section 3: Data Sheets 

The third section of your portfolio will be titled: **_Session Data_**. Your session data section will contain two data sheets:  

  1. **_Progress Monitoring Form_** (Form 7.4 can be found in the back of your text and can be downloaded from the publisher website): Complete a hypothetical progress monitoring form with the probe data for sessions 2-5 during the initial acquisition stage of training (i.e., four sessions worth of data).  This is your session probe data that you take at the beginning of the session to determine where to begin training in that session. Note: you will have to develop this after you have thought through the scenarios for the session data form described below. The long-term goal will likely be level 0 of your GAS. The short-term objective will be what you hope to achieve in the four sessions. Your data do not have to reflect meeting the short-term objective as this would have been set prior to initiating training and training sometimes goes quicker or slower than anticipated. Provide some comments on specific supports, engagement strategies and generalization programming that match the profile of your client as described on page 1. Also, be sure to make the progress of your client match the profile. Review Figure 7.7 in your textbook for an example.  
    
  2. **_Session Data from two consecutive sessions_** (Form 7.5 can be found in the back of your text or you can develop your data collection system): This part of the assignment will need to be integrated with the progress monitoring data. You will complete hypothetical data for two sessions. One session will show the data when the client was having difficulty learning one of the steps. It should be evident how you responded as the clinician. The other session will show data from successfully teaching two steps in succession. Note you are chaining steps together in every session and your data should reflect this. Review Figures 7.8, 7.9 and 7.10 in your textbook for samples.  
    
## Section 4: Video and Video Description 

The fourth section of your portfolio will be titled **Video Description**. You will write a paragraph describing the instruction shown in your video. _Explain which session from your session data form you are demonstrating and choose a session where the client made an error_. 

**_Video Components_**: You will make a demonstration video teaching an “actor” or “real” client to use your tool. Actor will need to know what to do in order to be consistent with your data. The session will be an excerpt from one of the two sessions above from which you developed session data 

The video will contain the following components: 

  * Minutes 1-2: Beginning of the session. This segment will show you introducing the session and administering the progress monitoring probe to evaluate retention. Clear language, scaffolding from the previous session will be evaluated. 

  * Minutes 2-5: Show a segment of training that you have identified in your paragraph. Video should incorporate key the principles of SI training, including error minimization and promotion of client engagement. 

  * Minutes 6: Session wrap up 
    

**Google Doc will be created for you to put link to your video**


## Portfolio Format

  * All written segments should be of high caliber with clear, cohesive, grammatical writing. Use references as appropriate that include an APA reference list. Put name on the first page on upper, right corner. 
  * Submit written assignments to Canvas 
  * Videos should be uploaded to YouTUbe under private, unlisted setting. Insert private YouTube link into Canvas written assignment submission page. 
    
## Portfolio Grading 

The project is worth 50 points. The point allocation for each section is listed below. Content for what we are looking for in each section is provided in the descriptions above. Points will be deducted for missing, erroneous, or incomplete components, or writing that does not have the above listed characteristics. Additionally, two points will be deducted for each day the portfolio is late. 

  * Section 1: 10 Points
  * Section 2: 5 Points 
  * Section 3: 15 Points 
  * Section 4: 15 Points 
  * Writing and Portfolio Presentation: 5 Points 
    
  * **ACE Award:** 30 Minutes 


# Putting Evidence into Practice Assignment 

**_Assignment:_** The purpose of this assignment is for you to translate existing evidence from paper into practice. You will each identity a cognitive intervention detailed in a research article that you feel would benefit a hypothetical client. You can use an article that was covered during the course or an article you identify independently. Keep in mind that the more recent the article, the better. Findings change frequently as research is continually conducted; therefore, it’s important to try and access the most current available research. Each of you will need to select a unique article, based on a first come, first serve basis. You may use the same intervention as another classmate, but you may not use the same article. When selecting your article, please keep in mind your hypothetical client profile, as you will need to provide a rationale for selecting the intervention. The article must demonstrate that the intervention is efficacious and support your rationale for selecting the specific intervention. You will read through the article and identify a series of key features detailed in the article necessary to demonstrate evidence. Those features will be documented on a spreadsheet that each of you will contribute to in order to establish a comprehensive reference tool to access once you have concluded the course. Then you will develop a narrative lesson plan discussing why the intervention is appropriate based upon the client’s profile and then detail how you would integrate the intervention into a clinical session. The lesson plan should briefly describe the intervention, provide a hypothesis and rationale as to why you believe it might benefit the client, and then discuss how it would be implemented during clinical sessions. 

**Due:** 3/11/21 

**_Preparation Considerations:_** Primary preparation is centered around selecting a client profile, which will guide your intervention search. You may use one of the client profiles referenced throughout the term, but feel free to develop a unique profile, especially students who have participated in BrICC. You will need to provide a clear rationale as to why you are selecting the intervention based upon the client’s clinical profile and reported deficits. 

Once you have identified an article, you will need to become familiar with the intervention in order to provide a sufficient description and how it would then be incorporated into a clinical session. If your article does not contain a clear description in the Methods section, then you will need to obtain that information from alternative sources. The purpose of this assignment is to replicate the real-world experience of accessing evidence and identifying how to implement the intervention into clinical sessions. 

**_Documentation:_** The document (see link below) will contain all of the information needed to guide the content you will want to identify in the article and report on. You will enter the information directly into the spreadsheet. For content that is not represented in the article, you will need to notate that on the spreadsheet. 

[Article Tables]() 

The narrative lesson plan should be approximately 2-pages in length, double-spaced, for the narrative portions. Please delineate between each of the various sections in the narrative by using headers to identify the (1) client profile, (2) intervention description, (3) clinical hypothesis and rationale, and (4) description of how you plan on embedding the intervention into a hypothetical clinical session. The narrative portions should be uploaded onto Canvas. 

**_Grading:_** 25 total points

  * 5 points - Fully completing the tables 
  * 5 points - Describing your client and rationale 
  * 5 points - Providing a detailed description of the intervention 
  * 5 points - Describing implementation of the intervention during a clinical session
  * 5 points - Using a clear and concise writing style, accurate grammar, and punctuation 
  
**Extra Credit Opportunity:_** 

Earn up to 10 extra credit points by developing a brief video of yourself implementing the strategy or at least a part of the strategy, similar to the video created for you Systematic Instruction assignment. You will briefly introduce the “client” to the intervention (1-2 minutes), engage in the activity (3-6 minutes), and wrap-up the activity, including a brief review of performance (3-6 minutes). Once you have completed the video, you will need produce a modified SOAP note, providing the O, A, and P sections. You may use a table or narrative description to describe the O section, a narrative for the A section, and bullet points for P section. Remember the rationale for the P section should be evidenced by the “client’s” reported performance in the O and A sections. 

**_Grading:_** - 10 total points

  * 5 points - Video
  * 5 points - Modified SOAP Note
  
**_Extra Credit:_** up to 10 points and 30 minutes of ACE hours 


# SIMUCASE "Larry" (CVLT Assessment)


# Asynchronous Lecture Discussion Questions 


