---
title: "Course Agenda"
---

| **Week** |  **Date**    | **Modality**            |           **Lead Instructor**                                                |                          **Topic**                                                        | **Readings** | **Due**       |
| :------- | :----------: | :----------------------------: | :----------------------------------------------------------------: | :------------------------------------------------------------------------------------------------------: | :----------: | :-----------: |
| 1a       |    1/5/21    |       Synchronous              |        Aaron & Jim           |          [Course Description; Introduction to cognitive rehabilitation; mechanism of injury](slides/Week1_21.pptx)        | [Koehler et al. (2012) IOM Report on Cognitive Rehabilitation](readings/Koehler et al 2012.pdf); [Turkstra et al. (2016)](readings/Turkstra et al 2016.pdf)       |                    | 
| 1b       |    1/7/21    |       Synchronous              |        Aaron & Jim           |          [Prevention; Overview of cognitive process areas; Overview of interventions](slides/Week1_21.pptx)        | Chapters 1 & 4, Sohlberg & Turkstra (2011)       |                    | 
| 1c       |    Home Lecture    |       Asynchronous              |                   |   [Rancho Levels Video](https://www.youtube.com/watch?v=ZWJUfSWYppM&t=1340s)                |        |                    | 
| 2a       |    1/12/21    |       Synchronous              |        Aaron & Jim           |          [Assessment and intervention fundamentals (MI, GAS)](slides/Week2_21_Assessment_Fundamentals_updated slides.pptx)       | [Turkstra et al. (2005)](readings/Turkstra et al. 2005.pdf); [Coelho et al. (2005)](readings/Coelho et al-2005.pdf) [Grant & Ponsford (2014)](readings/Grant&Ponsford 2014.pdf)       |                    | 
| 2b       |    1/14/21    |       Synchronous              |        Aaron            |          [Fundamentals Continued: therapeutic rapport, coaching & instruction models that promote resiliency, reflection, and self-efficacy](slides/Week2_21_Assessment_Fundamentals_updated slides.pdf)       | [Clinician's Guide to mTBI chapters 1 & 2](readings/Clinicians Guide Cognitive Rehabilitation mTBI.pdf); [Hillig, Ma, & Dorsch (2019)](readings/Hilig, Ma, Dorsch 2019.pdf); ["Is Emapthy Real?" podcast episode](https://www.listennotes.com/podcasts/therapy-insiders/is-empathy-real-conversation-HX1TcGK2lxJ/)       |       [**R&C 1 (in-class)**](chews/Review&Chew_1.docx)             | 
| 2c       |    Home Lecture    |       Asynchronous              |                   | [Case 1: Severe TBI](https://medone-comsci-thieme-com.libproxy.uoregon.edu/cockpits/cllogopedics/4251442484252747015/coCPeComCa0267/4-43?); [Case 2: mTBI](https://medone-comsci-thieme-com.libproxy.uoregon.edu/cockpits/cllogopedics/4251442484252747015/coCPeComCa0366/4-74?)                 |        |                     | 
| 3a       |    1/19/21    |       Synchronous              |        Jim           |          [Models of Attention](slides/Week3_21_Attention Lecture.pptx)        | [Dymowski et al. (2015)](readings/Dymowski 2015.pdf); [Serino et al. (2007)](readings/Serino 2007.pdf); [Seguin et al. (2017)](readings/Seguin et al. 2017.pdf); [working memory model 1](https://www.simplypsychology.org/working%20memory.html); [working memory model 2](http://mercercognitivepsychology.pbworks.com/w/page/61198759/Baddeley%27s%20Model%20of%20Working%20Memory)       |                    | 
| 3b       |    1/21/21    |       Synchronous              |        Jim           |          [DAT/APT](slides/Week3_21_Attention Lecture.pptx)       |     [APT-3 Manual pg. 1-37 plus client examples on pg. 48](tools/APT-3 Manual.pdf); [Sohlberg et al. (2014)](readings/Sohlberg et al. 2014.pdf)               | [**R&C 2 (in-class)**](chews/Review&Chew_2.docx); [Review and Chew 2 Attention Activities](tools/Review and Chew 2 Group Attention Activities.docx); [WALC-2](tools/walc_2.pdf)
| 3c       |    Home Lecture    |       Asynchronous              |                   |          [APT-3 Demonstration Video](https://www.youtube.com/watch?v=bRRM4yhqRiI)        |        |                     |  
| 4a       |    1/26/21    |       Synchronous              |        Jim & [Guest Lecturer: Heidi Iwashita](mailto:heidii@uoregon.edu)           |          [Overview of memory](slides/Week4_Memory_21.pptx); [Introduction to Dementia](slides/Dementia_Winter_2021.pptx); [ICF Dementia Handout](tools/ICF-Dementia.pdf); [GDS Handout](tools/GDS Handout.docx); [Retained Abilities in DAT Handout](tools/Retained Abilities in DAT.docx)        |  [long-term memory](https://www.simplypsychology.org/long-term-memory.html); [short term memory](https://www.simplypsychology.org/short-term-memory.html); [MSMM](https://www.simplypsychology.org/multi-store.html); [levels of processing](https://www.simplypsychology.org/levelsofprocessing.html); Chapter 1, pg. 7-9 Sohlberg & Turkstra (2011); [Shum et al. (2011)](readings/shum2011.pdf); [O'Neil-Pirozzi, Kennedy, & Sohlberg (2015)](readings/O'Neil-Pirozzi et al. 2015.pdf)        |                    | 
| 4b       |    1/28/21    |       Synchronous              |        Heidi           |          [Dementia Overview and Intervention](slides/Dementia_Winter_2021.pptx)        |        |                     | 
| 4c       |    Home Lecture    |       Asynchronous              |                   |          [Spaced Retrieval Video](https://www.youtube.com/watch?v=FiLzX1r8RVI)        |        |                     | 
| 5a       |    2/2/21    |       Synchronous              |        Aaron           |   [SI Lecture](slides/SystematicInstruction_ATCclass21.pptx); [SI Training Video](https://www.youtube.com/watch?v=En9v4XujWOc)        |  [Powell et al. (2012)](readings/Powell 2012.pdf)      |                    | 
| 5b       |    2/4/21    |       Synchronous              |        Aaron & Jim           |          [ATC Lecture](slides/SystematicInstruction_ATCclass21.pptx)        | Ch. 7 Sohlberg & Turkstra (2011) [Svoboda (2009)](readings/Svoboda 2009.pdf)      |                    | 
| 5c       |    Home Lecture    |       Asynchronous              |                   |                  |        |     **Test 1**               | 
| 6a       |    2/9/21    |       Synchronous              |        Aaron           |          [EF Theory](slides/ExecFunction21.pptx)        |        |   [**R&C 3 (in-class)**](chews/Review&Chew_3.docx)                | 
| 6b       |    2/11/21    |       Synchronous              |        Aaron           |          [EF Assessment & Treatment](slides/ExecFunction21.pptx)        |  Chapter 8 Sohlberg & Turkstra (2011); [Spikeman et al. (2010)](readings/Spikman et al 2010.pdf); [Stamenova & Levine (2018)](readings/Stamenova & Levine 2018.pdf)     |                   | 
| 6c       |    Home Lecture    |       Asynchronous              |                   |          [EF Video 1](https://www.youtube.com/watch?v=qAC-5hTK-4c); [EF Video 2](https://www.youtube.com/watch?v=i47_jiCsBMs)        |        |                   | 
| 7a       |    2/16/21    |       Synchronous              |        Guest Lecturer: Heidi            |          [Social Communication Overview: Assessment and Intervention](slides/Social Communication Lecture 2021 FINAL.pptx)        | [Ylvisaker (2006)](readings/Ylvisaker_2006.pdf); [Dahlberg (2007)](readings/Dahlberg 2007.pdf); [Hoepner & Olsen (2018)](readings/Hoepner_2018.pdf)       |                    | 
| 7b       |    2/18/21    |       Synchronous              |        Jim           |          [Concussion: Physiology, Symptoms, and Management](slides/Week 7_Concussion Lecture_21.pptx)        | [Giza & Hovda (2014)](readings/Giza&Hovda.pdf); [Biomechanics of concussion podcast](https://urldefense.com/v3/__https://podcasts.apple.com/us/podcast/ask-concussion-doc-complete-concussion-management/id1357687909?i=1000459292200__;!!C5qS4YX3!VbZAOmgAQYqyGcTyFOKtKGFDvmV7nuX3dU65rCBzqiQSPpwqXcS7oOt-VnulH9cmmsA0$); [Hardin & Kelly (2019)](readings/Hardin&Kelly 2019.pdf); [Wright & Sohlberg (2020)](readings/Wright et al_2020_Identification_of_Key_Therapy_Ingredients_for_SLPs.pdf); [RTL podcast](https://podcasts.apple.com/us/podcast/episode-69-return-to-school-work/id1357687909?i=1000455495336); [Concussion mental health podcast](https://podcasts.apple.com/us/podcast/episode-67-concussions-mental-health/id1357687909?i=1000453724696); [Nocebo effect podcast](https://podcasts.apple.com/us/podcast/episode-60-the-nocebo-effect/id1357687909?i=1000447620919); [Optional Reading - Post et al.(2017) ](readings/Post et al.pdf)      |     **SI Portfolio Due**               | 
| 7c       |    Home Lecture    |       Asynchronous              |                  |                   |     |      **Screenshot of Completed Simucase**        |
| 8a       |    2/23/21    |       Synchronous              |        Guest Lecturer: [Melaney Grenz](mailto:melaney.grenz@springfield.k12.or.us)           |          [Concussion Management in the K-12 School Setting](slides/School Based TBI Presentation.pptx)        | [Gioia (2016)](readings/Gioia 2016.pdf); [Dachtyl & Morales (2017)](readings/Dachtyl&Morales 2017.pdf); [Knollman-Porter (2019)](readings/Knollman-Porter 2019.pdf); [ABI in Criminal Justice System Video](https://www.youtube.com/watch?v=UJq6VftF030&feature=youtu.be)       |                    | 
| 8b       |    2/25/21    |       Synchronous              |                   |          [Right Hemisphere Disorder: Management of Visual Neglect](slides/lftneglect20.pptx)        |   [RHD Podcast Episode](https://soundcloud.com/ancds/ep-11-a-conversation-with-margaret-blake-right-hemisphere-damage-and-disorders)     |                     | 
| 8c       |    Home Lecture    |       Asynchronous              |                   |                |        |       **Test 2**             | 
| 9a       |    3/2/21    |       Synchronous              |        Guest Lecturer: [Amanda Thompson](mailto:athomp13@uoregon.edu)           |          [Acute Inpatient Settings - Assessment and Intervention](slides/Cog_rehab_acute_care_21.pptx)     | [Valitchka & Turkstra (2013)](readings/Valitchka&Turkstra2013.pdf); [Turkstra (2013)](readings/Turkstra 2013.pdf); [Addenbrooke's Cognitive Examination](tools/ADDENBROOKE’S COGNITIVE EXAMINATION.pdf); [Family Guide to the Rancho Levels of Cognitive Functioning](tools/Rancho levels edu for family.pdf)       |                    | 
| 9b       |    3/4/21    |       Synchronous              |        Aaron/Jim/Heidi/Amanda           |          [Simulation Strategy Training Lab](simlab.html)        |        |                    | 
| 9c       |    Home Lecture    |       Asynchronous              |                   |          [Client video](https://youtu.be/fqgVaVh9woA)        |        |   **Develop questions for final panel on 3/11**                 | 
| 10a       |    3/9/21    |       Synchronous              |        Guest lecturer: [Priya Kucheria](mailto:priyak@uoregon.edu)           |          [Translating the Evidence](slides/Translating the evidence_presentation.pptx)        |  [Shimizu et al. (2019)](readings/Malnutrition predicts prognosis in stroke-related dysphagia_Shimizu_2_2019.pdf); [Pérez-Ros et al. (2019)](readings/Perez_Ros.pdf); [Assessing The Applicability of Studies When Comparing Medical Interventions](readings/assessing_applicability_guidance_methods.pdf)       |                    | 
| 10b       |    3/11/21    |       Synchronous              |        Aaron & Jim            |          Guest panel with former BrICC client and his spouse        |        |   **EBP Assignment Due**                 | 
| 10c       |    Home Lecture    |       Asynchronous              |                   |          Office hours to answer questions prior to final        |        |                    | 



|         |           |
| :-----: | :-------: |
| Final Exam Date | Friday March 19th |
| Final Exam Time | 8:00 AM |
| [Final Exam Zoom Link](https://zoom.us/j/94922601451?pwd=Zlp2eU0vTkQ1N2I1Q1lSOVIyUGlwZz09) | 